name: backend-usuarios-ci

on:
  push:
    branches: [main, devel]
  pull_request:
    branches:
      - main
      - devel
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: ðŸ“¬ Caching
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/dist
          key: ${{ runner.os }}-jest-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('/.{js,jsx,ts,tsx}') }}
          restore-keys: |
            ${{ runner.os }}-jest-${{ hashFiles('**/package-lock.json') }}-

      - name: ðŸ§° Instala bibliotecas e dependÃªncias
        run: npm i

      - name: ðŸ§ª Roda suÃ­te de testes
        run: npm test

  # sonarcloud:
  #   name: sonarcloud
  #   needs: [test]
  #   runs-on: ubuntu-latest
  #   continue-on-error: true
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: ðŸ“¬ Caching
  #       uses: actions/cache@v3
  #       with:
  #         path: |
  #           ${{ github.workspace }}/node_modules
  #           ${{ github.workspace }}/dist
  #         key: ${{ runner.os }}-jest-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.{js,jsx,ts,tsx}') }}
  #         restore-keys: |
  #           ${{ runner.os }}-jest-${{ hashFiles('**/package-lock.json') }}-

  #     - name: ðŸ§° Instala bibliotecas e dependÃªncias
  #       run: npm i

  #     # todo quando tiver eslint
  #     # - name: ðŸ“œ RelatÃ³rio do eslint
  #     #   run: npx eslint -f json -o reports/eslint-report.json src || true

  #     - name: ðŸ§ª Testes e cobertura
  #       run: JEST_SONAR=jest-sonar CI=true npm test -- --coverage

  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
